### ISSUE TITLE
Group Members Page // Identify Group Admins

### ISSUE THREAD

**Issue by state-hiu** [ebola-geonode/ebola_geonode#30]
Could we add some type of manager flag for group managers next to their name in the list of members?  Just a piece of white text that says "Manager" with blue background.

![image](https://cloud.githubusercontent.com/assets/2079497/5073072/5af84e1c-6e4d-11e4-9419-aebb3abba87b.png)

**Comment by jj0hns0n** [comment]
Fixed upstream and in http://107.20.114.56/

**Comment by state-hiu** [comment]
This is separate than https://github.com/ebola-geonode/ebola_geonode/issues/27.  We should have a blue "Manager" label right next to each member in the members list if they are a manager.  This isn't fixed upstream.  See below for mockup.

![image](https://cloud.githubusercontent.com/assets/2079497/5168377/95d0f58c-73cc-11e4-94b6-6ab8c045ce23.png)

**Comment by jj0hns0n** [comment]
Ah, you are right. But the managers are displayed on the right hand side in
a list.

We should file this one upstream though.

**Comment by state-hiu** [comment]
Yes, but I think we should still identify them in the big list of members since the list of members can get really long.  You shouldn't need to scroll back to the top to check if someone is a manager.

**Comment by jj0hns0n** [comment]
Yeah, it makes sense, lets just file upstream. Should be an easy thing to
implement.

**Comment by state-hiu** [comment]
Submitted related PR upstream (https://github.com/GeoNode/geonode/pull/1942).  I'm just going to close this.  It's complicated to add the exact feature described in this issue, because the group detail page iterates through the standard profile_list_item template.
